#-- copyright
# OpenProject is a project management system.
# Copyright (C) 2012-2018 the OpenProject Foundation (OPF)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2018 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See doc/COPYRIGHT.rdoc for more details.
#++

language: ruby

rvm:
  - 2.6.1

sudo: required
dist: xenial

cache:
  bundler: true
  directories:
    - public/assets
    - app/assets/javascripts/bundles
    - app/assets/javascripts/locales

branches:
  only:
    - master
    - dev
    - /^(stable|release)\/.*$/
    - /^.*(_specs)$/

env:
  global:
    - CI=true
    - RAILS_ENV=test


before_install:

  # work around https://github.com/travis-ci/travis-ci/issues/8969
  - travis_retry gem update --system
  # Don't install 1.16.3
  - gem install bundler -v 2.0.1 --no-document

  # Install Node latest LTS
  # This should only be necessary when preparing the cache or for npm test runs
  # but installing later fails for unknown reasons.
  - nvm install --lts

bundler_args: --binstubs --without development production docker

stages:
  - prepare cache
  - test

jobs:
  include:
    - stage: prepare cache
      name: 'Prepare cache'
      script:
        # Run the dangerfile
        - bundle exec danger --fail-on-errors=true || travis_terminate 1;
        # Set up caching
        - bash script/ci/db_setup.sh
        - bash script/ci/cache_prepare.sh
    - stage: test
      name: 'units'
      script:
        - bash script/ci/setup.sh units
        - bash script/ci/runner.sh units

addons:
  chrome: stable
  postgresql: "9.6"
